# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # add this after 'DEPREC' message in logs
    twig:
        mode: lazy

    filter_sets:
        # cache: ~

        # the name of the "filter set"
        property_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 360x230 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [360, 230], mode: outbound }
                
        property_medium:
            quality: 75
            filters:
                thumbnail: { size: [600, 450], mode: outbound }
                # create a 30px black border in top and bottom and center the thumbnail on a black background
                background: { size: [600, 480], position: center, color: '#333' }
