vich_uploader:
    db_driver: orm # or mongodb or phpcr
    metadata:
        type: attribute
    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties' # repertory of saved images, corresponding uri prefix
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer